### ISSUE TITLE
Configurable product problem

### ISSUE THREAD

**Issue by JelleGroenendal** [Agence-DnD/PIMGento-2-API#48]
After updating to 100.1.3 i ran in to the following issue:

[07:12:50] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'v.parent' in 'on clause', query was: UPDATE `tmp_pimgento_entities_product` AS `e`
 INNER JOIN `pimgento_product_model` AS `v` ON v.parent IS NOT NULL AND e.parent = v.code
SET `e`.`parent` = `v`.`parent`

When i look in the code i cant seem to find any reference that pimgento_product_model should have parent.
The piece of code that i think is at fault is:
https://github.com/Agence-DnD/PIMGento-2-API/blob/d6c5c0df870a36682ccb842bf27d6752e4f5ee61/Job/Product.php#L409
Is this part of the code complete? @magentix 
It might also be the case that this happens because we dont have configurable products at the moment.

**Comment by Dnd-Gimix** [comment]
Hello @JelleGroenendal ,

You are right, this issue happens because you don't have configurable product.
Our team already fixed it in this PR : https://github.com/Agence-DnD/PIMGento-2-API/pull/50
Could you patch your code with thoses changes ?

This update should be released next week.
Have a good day.

Regards,

**Comment by Dnd-Gimix** [comment]
Hello @JelleGroenendal ,

The fix is officially released in the new 100.1.4 version.

Have a nice day !

Regards,
